/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HealthGuaranteeRouteImport } from './routes/health-guarantee'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PuppiesRouteImport } from './routes/puppies'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as PuppiesSlugRouteImport } from './routes/puppies.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminEnquiriesRouteImport } from './routes/_authenticated/admin.enquiries'
import { Route as AuthenticatedAdminPuppiesRouteImport } from './routes/_authenticated/admin.puppies'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminPuppiesIndexRouteImport } from './routes/_authenticated/admin.puppies.index'
import { Route as AuthenticatedAdminPuppiesIdRouteImport } from './routes/_authenticated/admin.puppies.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthGuaranteeRoute = HealthGuaranteeRouteImport.update({
  id: '/health-guarantee',
  path: '/health-guarantee',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PuppiesRoute = PuppiesRouteImport.update({
  id: '/puppies',
  path: '/puppies',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PuppiesSlugRoute = PuppiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PuppiesRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminEnquiriesRoute =
  AuthenticatedAdminEnquiriesRouteImport.update({
    id: '/enquiries',
    path: '/enquiries',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPuppiesRoute =
  AuthenticatedAdminPuppiesRouteImport.update({
    id: '/puppies',
    path: '/puppies',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPuppiesIndexRoute =
  AuthenticatedAdminPuppiesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminPuppiesRoute,
  } as any)
const AuthenticatedAdminPuppiesIdRoute =
  AuthenticatedAdminPuppiesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminPuppiesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/health-guarantee': typeof HealthGuaranteeRoute
  '/privacy': typeof PrivacyRoute
  '/puppies': typeof PuppiesRouteWithChildren
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/puppies/$slug': typeof PuppiesSlugRoute
  '/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/admin/puppies': typeof AuthenticatedAdminPuppiesRouteWithChildren
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/puppies/$id': typeof AuthenticatedAdminPuppiesIdRoute
  '/admin/puppies/': typeof AuthenticatedAdminPuppiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/health-guarantee': typeof HealthGuaranteeRoute
  '/privacy': typeof PrivacyRoute
  '/puppies': typeof PuppiesRouteWithChildren
  '/terms': typeof TermsRoute
  '/puppies/$slug': typeof PuppiesSlugRoute
  '/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/puppies/$id': typeof AuthenticatedAdminPuppiesIdRoute
  '/admin/puppies': typeof AuthenticatedAdminPuppiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/health-guarantee': typeof HealthGuaranteeRoute
  '/privacy': typeof PrivacyRoute
  '/puppies': typeof PuppiesRouteWithChildren
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/puppies/$slug': typeof PuppiesSlugRoute
  '/_authenticated/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/_authenticated/admin/puppies': typeof AuthenticatedAdminPuppiesRouteWithChildren
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/puppies/$id': typeof AuthenticatedAdminPuppiesIdRoute
  '/_authenticated/admin/puppies/': typeof AuthenticatedAdminPuppiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/health-guarantee'
    | '/privacy'
    | '/puppies'
    | '/terms'
    | '/admin'
    | '/puppies/$slug'
    | '/admin/enquiries'
    | '/admin/puppies'
    | '/admin/settings'
    | '/admin/'
    | '/admin/puppies/$id'
    | '/admin/puppies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/health-guarantee'
    | '/privacy'
    | '/puppies'
    | '/terms'
    | '/puppies/$slug'
    | '/admin/enquiries'
    | '/admin/settings'
    | '/admin'
    | '/admin/puppies/$id'
    | '/admin/puppies'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/health-guarantee'
    | '/privacy'
    | '/puppies'
    | '/terms'
    | '/_authenticated/admin'
    | '/puppies/$slug'
    | '/_authenticated/admin/enquiries'
    | '/_authenticated/admin/puppies'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/puppies/$id'
    | '/_authenticated/admin/puppies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  HealthGuaranteeRoute: typeof HealthGuaranteeRoute
  PrivacyRoute: typeof PrivacyRoute
  PuppiesRoute: typeof PuppiesRouteWithChildren
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health-guarantee': {
      id: '/health-guarantee'
      path: '/health-guarantee'
      fullPath: '/health-guarantee'
      preLoaderRoute: typeof HealthGuaranteeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puppies': {
      id: '/puppies'
      path: '/puppies'
      fullPath: '/puppies'
      preLoaderRoute: typeof PuppiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/puppies/$slug': {
      id: '/puppies/$slug'
      path: '/$slug'
      fullPath: '/puppies/$slug'
      preLoaderRoute: typeof PuppiesSlugRouteImport
      parentRoute: typeof PuppiesRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/enquiries': {
      id: '/_authenticated/admin/enquiries'
      path: '/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AuthenticatedAdminEnquiriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/puppies': {
      id: '/_authenticated/admin/puppies'
      path: '/puppies'
      fullPath: '/admin/puppies'
      preLoaderRoute: typeof AuthenticatedAdminPuppiesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/puppies/': {
      id: '/_authenticated/admin/puppies/'
      path: '/'
      fullPath: '/admin/puppies/'
      preLoaderRoute: typeof AuthenticatedAdminPuppiesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminPuppiesRoute
    }
    '/_authenticated/admin/puppies/$id': {
      id: '/_authenticated/admin/puppies/$id'
      path: '/$id'
      fullPath: '/admin/puppies/$id'
      preLoaderRoute: typeof AuthenticatedAdminPuppiesIdRouteImport
      parentRoute: typeof AuthenticatedAdminPuppiesRoute
    }
  }
}

interface AuthenticatedAdminPuppiesRouteChildren {
  AuthenticatedAdminPuppiesIdRoute: typeof AuthenticatedAdminPuppiesIdRoute
  AuthenticatedAdminPuppiesIndexRoute: typeof AuthenticatedAdminPuppiesIndexRoute
}

const AuthenticatedAdminPuppiesRouteChildren: AuthenticatedAdminPuppiesRouteChildren =
  {
    AuthenticatedAdminPuppiesIdRoute: AuthenticatedAdminPuppiesIdRoute,
    AuthenticatedAdminPuppiesIndexRoute: AuthenticatedAdminPuppiesIndexRoute,
  }

const AuthenticatedAdminPuppiesRouteWithChildren =
  AuthenticatedAdminPuppiesRoute._addFileChildren(
    AuthenticatedAdminPuppiesRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminEnquiriesRoute: typeof AuthenticatedAdminEnquiriesRoute
  AuthenticatedAdminPuppiesRoute: typeof AuthenticatedAdminPuppiesRouteWithChildren
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminEnquiriesRoute: AuthenticatedAdminEnquiriesRoute,
  AuthenticatedAdminPuppiesRoute: AuthenticatedAdminPuppiesRouteWithChildren,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PuppiesRouteChildren {
  PuppiesSlugRoute: typeof PuppiesSlugRoute
}

const PuppiesRouteChildren: PuppiesRouteChildren = {
  PuppiesSlugRoute: PuppiesSlugRoute,
}

const PuppiesRouteWithChildren =
  PuppiesRoute._addFileChildren(PuppiesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  HealthGuaranteeRoute: HealthGuaranteeRoute,
  PrivacyRoute: PrivacyRoute,
  PuppiesRoute: PuppiesRouteWithChildren,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
